---
title: "Weekly Summary Template"
author: "Author Name"
title-block-banner: true
title-block-style: default
toc: true
format: html
# format: pdf
---

---

## Tuesday, Jan 17

::: {.callout-important}
## TIL

Include a _very brief_ summary of what you learnt in this class here. 

Today, I learnt the following concepts in class:

1. ? follow by the function name will bring up an R document with the complete use of the function. 
1. You can create functions with X <- function(){}
1. The line of best fit minimizes the residuals.
:::

Provide more concrete details here. You can also use footenotes[^footnote] if you like

For example: 
in class we learnt we learnt about the `map` function from the `purrr` package. 


```{R}
X <- function(){ 
  matrix(
    c(1,2,3,4,5,6,7,8,9,1,2,3),
    nrow = 3,
    byrow = TRUE
}
```

```{R}
X
```

## Thursday, Jan 19



::: {.callout-important}
## TIL

Include a _very brief_ summary of what you learnt in this class here. 

Today, I learnt the following concepts in class:

1. When we see small p value them be reject the null hypothesis. 
1. The function lm(), helps to find the least squares line
1. Item 3
:::

Provide more concrete details here, e.g., 

In class we learnt how to use the `map` function to create multiple regression diagnostic plots

```{R}

```


[^footnote]: You can include some footnotes here